### PR TITLE
Contribute my project "CodeAura" 

### PR DESCRIPTION
**Pull request by REHAN-18**
**CodeAura** is a custom IDE code editor built with the MERN stack for HTML, CSS, and JavaScript development.

### CODE REVIEW

**Comment by darkhorse404** [comment]
An innovative idea but
🛑 Remove the `node_modules` folder. This folder is only for environment building locally and **NOT to be pushed on Git or GitHub**.
Also Recheck the PR for any other problems

**Comment by REHAN-18** [comment]
ok sir....

**Comment by REHAN-18** [comment]
please assign me this issue under gssoc-ext and hactoberfest level2 so that i can start working immediately.

**Comment by REHAN-18** [comment]
@darkhorse404 updated my bugs!!

**Comment by darkhorse404** [comment]
The `node_modules` folder is still there. It has to be removed.

**Comment by REHAN-18** [comment]
@darkhorse404 removed the node model

**Pull request merged**
